/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.jacoes.ui;

import java.io.File;
import javax.swing.DefaultListModel;

public class BaseAtivos extends javax.swing.JInternalFrame {

    /**
     * Creates new form BaseAtivos
     */
    public BaseAtivos() {
        initComponents();
        dlmAtivos = new DefaultListModel();
        jlBaseAtivos.setModel(dlmAtivos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlBaseAtivos = new javax.swing.JList<>();

        setPreferredSize(new java.awt.Dimension(143, 500));

        jlBaseAtivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlBaseAtivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBaseAtivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlBaseAtivos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlBaseAtivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBaseAtivosMouseClicked
        // TODO add your handling code here:
        itemSelecionado = jlBaseAtivos.getSelectedValue();
    }//GEN-LAST:event_jlBaseAtivosMouseClicked
    
    public String getSelectedItem(){
        return itemSelecionado;
    }
    
    public void setSelectedItem(String itemSelecionado){
        this.itemSelecionado = itemSelecionado;
    }
    
    public void setDiretorio(String diretorio) {
        this.diretorio = diretorio;
        dlmAtivos.clear();
        carregarAtivos();
    }
    
    private String getTicker(String nome){
        String ticker = nome.substring(0, nome.lastIndexOf("."));
        return ticker;
    }
    
    private void carregarAtivos() {
        File dir = new File(this.diretorio);
        File [] arquivos = dir.listFiles();
        String nomeArquivo;
        
        for (File arquivo : arquivos) {
            nomeArquivo = arquivo.getName();
            if(nomeArquivo.substring(nomeArquivo.lastIndexOf(".") + 1, nomeArquivo.length()).equals("csv")){
                dlmAtivos.addElement(getTicker(arquivo.getName()));
            }
        }
    }
    
    private DefaultListModel dlmAtivos;
    private String diretorio;
    private String itemSelecionado;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlBaseAtivos;
    // End of variables declaration//GEN-END:variables
}
