/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.jacoes.ui;

import br.edu.ifsp.jacoes.data.LeitorCSV;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author caca1
 */
public class Configurações extends javax.swing.JFrame {
    /**
     * Creates new form SelecionarArquivo
     */
    public Configurações() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfDiretorio = new javax.swing.JTextField();
        jmSalvarAlteracoesDiretorio = new javax.swing.JButton();
        jmEscolherDiretorio = new javax.swing.JButton();
        jmCancelarEscolhaDiretorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Diretório:");

        jtfDiretorio.setEditable(false);
        jtfDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDiretorioActionPerformed(evt);
            }
        });

        jmSalvarAlteracoesDiretorio.setText("Salvar");
        jmSalvarAlteracoesDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalvarAlteracoesDiretorioActionPerformed(evt);
            }
        });

        jmEscolherDiretorio.setText("Escolher Diretório");
        jmEscolherDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEscolherDiretorioActionPerformed(evt);
            }
        });

        jmCancelarEscolhaDiretorio.setText("Cancelar");
        jmCancelarEscolhaDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCancelarEscolhaDiretorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jmEscolherDiretorio)
                .addGap(86, 86, 86)
                .addComponent(jmSalvarAlteracoesDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jmCancelarEscolhaDiretorio)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jtfDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmEscolherDiretorio)
                    .addComponent(jmSalvarAlteracoesDiretorio)
                    .addComponent(jmCancelarEscolhaDiretorio))
                .addGap(24, 24, 24))
        );

        getAccessibleContext().setAccessibleName("Selecionar diretório");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmEscolherDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEscolherDiretorioActionPerformed
       
        JFileChooser fileChooser = new JFileChooser();
        // Nome
       fileChooser.setDialogTitle("Procurar arquivo");
       fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
       
       //Seleciona apenas arquivos com extensão csv
       FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivo", "csv");
       fileChooser.setFileFilter(filter);
       
       int retorno = fileChooser.showOpenDialog(this); 
       
       if(retorno == JFileChooser.APPROVE_OPTION){
           //Preenchimento do diretório
           file = fileChooser.getSelectedFile();
           jtfDiretorio.setText(file.getPath());
       }
    }//GEN-LAST:event_jmEscolherDiretorioActionPerformed

    private void jtfDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDiretorioActionPerformed

    }//GEN-LAST:event_jtfDiretorioActionPerformed

    private void jmCancelarEscolhaDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCancelarEscolhaDiretorioActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jmCancelarEscolhaDiretorioActionPerformed

    private void jmSalvarAlteracoesDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalvarAlteracoesDiretorioActionPerformed
        String caminho = file.getPath();
        jtfDiretorio.setText(caminho);
        diretorio.setArquivo(caminho);
        this.setVisible(false);
    }//GEN-LAST:event_jmSalvarAlteracoesDiretorioActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configurações().setVisible(true);
            }
        });
    }
    private LeitorCSV diretorio = new LeitorCSV(); 
    private File file;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jmCancelarEscolhaDiretorio;
    private javax.swing.JButton jmEscolherDiretorio;
    private javax.swing.JButton jmSalvarAlteracoesDiretorio;
    private javax.swing.JTextField jtfDiretorio;
    // End of variables declaration//GEN-END:variables
}
