/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.jacoes.ui;

import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.beans.PropertyVetoException;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.plot.Marker;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.chart.ui.RectangleAnchor;

/**
 *
 * @author bruno e carlos
 */
public class JAcoes extends javax.swing.JFrame {
    
    public JAcoes() {
        initComponents();
        this.setSize(800, 600);
    }      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmInicio = new javax.swing.JMenu();
        jmSelecionarArquivo = new javax.swing.JMenuItem();
        jmiSobre = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();
        jmFerramentas = new javax.swing.JMenu();
        jmiPlotarGrafico = new javax.swing.JMenuItem();
        jmiBaseAtivos = new javax.swing.JMenuItem();
        jmiCalcularMMA = new javax.swing.JMenuItem();
        jmiPeriodo = new javax.swing.JMenuItem();
        jmConfig = new javax.swing.JMenu();
        jmiAbrirConfig = new javax.swing.JMenuItem();
        jmAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );

        jmInicio.setText("Início");

        jmSelecionarArquivo.setText("Selecionar Arquivo");
        jmSelecionarArquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSelecionarArquivoMouseClicked(evt);
            }
        });
        jmSelecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSelecionarArquivoActionPerformed(evt);
            }
        });
        jmInicio.add(jmSelecionarArquivo);

        jmiSobre.setText("Sobre");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jmInicio.add(jmiSobre);

        jmiSair.setText("Sair");
        jmInicio.add(jmiSair);

        jMenuBar1.add(jmInicio);

        jmFerramentas.setText("Ferramentas");

        jmiPlotarGrafico.setText("Plotar Gráfico");
        jmiPlotarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPlotarGraficoActionPerformed(evt);
            }
        });
        jmFerramentas.add(jmiPlotarGrafico);

        jmiBaseAtivos.setText("Base de Ativos");
        jmiBaseAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBaseAtivosActionPerformed(evt);
            }
        });
        jmFerramentas.add(jmiBaseAtivos);

        jmiCalcularMMA.setText("Calcular MMA");
        jmFerramentas.add(jmiCalcularMMA);

        jmiPeriodo.setText("Sel. Período");
        jmFerramentas.add(jmiPeriodo);

        jMenuBar1.add(jmFerramentas);

        jmConfig.setText("Config.");

        jmiAbrirConfig.setText("Abrir");
        jmiAbrirConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbrirConfigActionPerformed(evt);
            }
        });
        jmConfig.add(jmiAbrirConfig);

        jMenuBar1.add(jmConfig);

        jmAjuda.setText("Ajuda");
        jMenuBar1.add(jmAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiBaseAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBaseAtivosActionPerformed
        // TODO add your handling code here:
        jBaseAtivos = new BaseAtivos();
        jPanel3.add(jBaseAtivos);
        jBaseAtivos.setVisible(true);
        jBaseAtivos.setDiretorio(jConfiguracoes.getDiretorio());
        
        try {
            jBaseAtivos.setMaximum(true);
        } catch (PropertyVetoException ex) {
            System.err.println("Não foi possível maximizar o painel de ativos!");
        }
    }//GEN-LAST:event_jmiBaseAtivosActionPerformed

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void jmiPlotarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPlotarGraficoActionPerformed
        // TODO add your handling code here:
        for (Component cp : jPanel2.getComponents() ){
            jPanel2.remove(cp);
        }
        
        try{
            Grafico g = new Grafico();
            ChartPanel chart = g.plotarGrafico(jBaseAtivos.getSelectedItem(), jConfiguracoes.getDiretorio()+"/"+jBaseAtivos.getSelectedItem()+".csv");
            jPanel2.setLayout(new java.awt.BorderLayout());
            jPanel2.add(chart); 
            jPanel2.validate();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JAcoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiPlotarGraficoActionPerformed

    private void jmSelecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSelecionarArquivoActionPerformed
        
    }//GEN-LAST:event_jmSelecionarArquivoActionPerformed

    private void jmSelecionarArquivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSelecionarArquivoMouseClicked
        
    }//GEN-LAST:event_jmSelecionarArquivoMouseClicked

    private void jmiAbrirConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbrirConfigActionPerformed
        // TODO add your handling code here:
        jConfiguracoes = new Configuracoes();
        jConfiguracoes.setVisible(true);
    }//GEN-LAST:event_jmiAbrirConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAcoes().setVisible(true);
            }
        });
    }
    
    BaseAtivos jBaseAtivos;
    Configuracoes jConfiguracoes;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmConfig;
    private javax.swing.JMenu jmFerramentas;
    private javax.swing.JMenu jmInicio;
    private javax.swing.JMenuItem jmSelecionarArquivo;
    private javax.swing.JMenuItem jmiAbrirConfig;
    private javax.swing.JMenuItem jmiBaseAtivos;
    private javax.swing.JMenuItem jmiCalcularMMA;
    private javax.swing.JMenuItem jmiPeriodo;
    private javax.swing.JMenuItem jmiPlotarGrafico;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSobre;
    // End of variables declaration//GEN-END:variables
}
